import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Auto-generated sidebar.
 *
 * Category labels and ordering are defined per folder via `_category_.json`.
 * Adding a new doc page is as simple as dropping a markdown file into the
 * appropriate `docs/NN-category/` folder with a `sidebar_position` in its
 * frontmatter.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
